package com.softserve.academy.spaced.repetition.audit;

public enum AuditingActionType {
    SIGN_IN("SIGN_IN"),
    SIGN_IN_VIA_GOOGLE("SIGN_IN_VIA_GOOGLE"),
    SIGN_IN_VIA_FACEBOOK("SIGN_IN_VIA_FACEBOOK"),
    SIGN_UP("SIGN_UP"),
    SIGN_UP_GOOGLE("SIGN_UP_GOOGLE"),
    SIGN_UP_FACEBOOK("SIGN_UP_FACEBOOK"),
    SIGN_OUT("SIGN_OUT"),
    VIEW_TOP_CATEGORY("VIEW_TOP_CATEGORY"),
    VIEW_ALL_CATEGORY("VIEW_ALL_CATEGORY"),
    VIEW_CATEGORY("VIEW_CATEGORY"),
    CREATE_CATEGORY("CREATE_CATEGORY"),
    EDIT_CATEGORY("EDIT_CATEGORY"),
    VIEW_CARD_BY_COURSE_AND_DECK("VIEW_CARD_BY_COURSE_AND_DECK"),
    VIEW_CARD_BY_CATEGORY_AND_DECK("VIEW_CARD_BY_CATEGORY_AND_DECK"),
    CREATE_CARD_BY_COURSE_AND_DECK("CREATE_CARD_BY_COURSE_AND_DECK"),
    CREATE_CARD_BY_CATEGORY_AND_DECK("CREATE_CARD_BY_CATEGORY_AND_DECK"),
    EDIT_CARD_BY_COURSE_AND_DECK("EDIT_CARD_BY_COURSE_AND_DECK"),
    EDIT_CARD_BY_CATEGORY_AND_DECK("EDIT_CARD_BY_CATEGORY_AND_DECK"),
    DELETE_CARD("DELETE_CARD"),
    RATE_CARD("RATE_CARD"),
    VIEW_COURSES("VIEW_COURSES"),
    VIEW_TOP_COURSES("VIEW_TOP_COURSES"),
    VIEW_COURSES_BY_CATEGORY("VIEW_COURSES_BY_CATEGORY"),
    VIEW_DECKS_BY_CATEGORY("VIEW_DECK_BY_CATEGORY"),
    VIEW_DECKS_BY_COURSE("VIEW_DECK_BY_COURSE");

    private final String actionDescription;

    AuditingActionType(String value) {
        actionDescription = value;
    }

    public String getActionDescription() {
        return actionDescription;
    }
}
