package com.softserve.academy.spaced.repetition.audit;

public enum AuditingActionType {
    SIGN_IN("SIGN_IN"),
    SIGN_IN_VIA_GOOGLE("SIGN_IN_VIA_GOOGLE"),
    SIGN_IN_VIA_FACEBOOK("SIGN_IN_VIA_FACEBOOK"),
    SIGN_UP("SIGN_UP"),
    SIGN_UP_GOOGLE("SIGN_UP_GOOGLE"),
    SIGN_UP_FACEBOOK("SIGN_UP_FACEBOOK"),
    VIEW_ALL_USERS("SET_ACCOUNT_BLOCKED"),
    VIEW_ONE_USER("SET_ACCOUNT_BLOCKED"),
    SET_ACCOUNT_BLOCKED("SET_ACCOUNT_BLOCKED"),
    SET_ACCOUNT_DELETED("SET_ACCOUNT_DELETED"),
    SET_ACCOUNT_ACTIVE("SET_ACCOUNT_ACTIVE"),
    ADD_DECK_TO_USER_FOLDER("ADD_DECK_TO_USER_FOLDER"),
    REMOVE_DECK_FROM_USER_FOLDER("REMOVE_DECK_FROM_USER_FOLDER"),
    VIEW_DECKS_FROM_USER_FOLDER("VIEW_DECKS_FROM_USER_FOLDER"),
    ADD_DECK_TO_FOLDER("ADD_DECK_TO_FOLDER"),
    VIEW_DECK_IN_FOLDER("VIEW_DECK_IN_FOLDER"),
    START_LEARNING_VIA_FOLDER("START_LEARNING_VIA_FOLDER"),
    VIEW_TOP_CATEGORY("VIEW_TOP_CATEGORY"),
    VIEW_ALL_CATEGORY("VIEW_ALL_CATEGORY"),
    VIEW_CATEGORY("VIEW_CATEGORY"),
    CREATE_CATEGORY("CREATE_CATEGORY"),
    EDIT_CATEGORY("EDIT_CATEGORY"),
    START_LEARNING_VIA_COURSE("START_LEARNING_VIA_COURSE"),
    START_LEARNING_VIA_CATEGORY("START_LEARNING_VIA_CATEGORY"),
    CREATE_CARD_VIA_COURSE_AND_DECK("CREATE_CARD_VIA_COURSE_AND_DECK"),
    CREATE_CARD_VIA_CATEGORY_AND_DECK("CREATE_CARD_VIA_CATEGORY_AND_DECK"),
    EDIT_CARD_VIA_COURSE_AND_DECK("EDIT_CARD_VIA_COURSE_AND_DECK"),
    EDIT_CARD_VIA_CATEGORY_AND_DECK("EDIT_CARD_VIA_CATEGORY_AND_DECK"),
    DELETE_CARD("DELETE_CARD"),
    RATE_CARD("RATE_CARD"),
    VIEW_COURSES("VIEW_COURSES"),
    VIEW_TOP_COURSES("VIEW_TOP_COURSES"),
    VIEW_COURSES_VIA_CATEGORY("VIEW_COURSES_VIA_CATEGORY"),
    ADD_COURSE("ADD_COURSE"),
    CREATE_COURSE("CREATE_COURSE"),
    DELETE_COURSE("DELETE_COURSE"),
    VIEW_DECKS_VIA_CATEGORY("VIEW_DECKS_VIA_CATEGORY"),
    CREATE_DECK_IN_CATEGORY("CREATE_DECK_IN_CATEGORY"),
    CREATE_DECK_IN_COURSE("CREATE_DECK_IN_COURSE"),
    EDIT_DECK("EDIT_DECK"),
    DELETE_DECK("DELETE_DECK"),
    VIEW_DECKS_VIA_COURSE("VIEW_DECK_VIA_COURSE");

    private final String actionDescription;

    AuditingActionType(String value) {
        actionDescription = value;
    }

    public String getActionDescription() {
        return actionDescription;
    }
}
